import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression

# Configure page layout
st.set_page_config(
    page_title="VR Business Forecasting Lab",
    page_icon="📊",
    layout="wide"
)

# Custom CSS for enhanced dark sidebar styling with white text
st.markdown("""
    <style>
    /* Force sidebar dark background */
    [data-testid="stSidebar"] {
        background-color: #0e1117;
        padding-top: 1rem;
    }
    
    /* Force all text elements in sidebar to pure white */
    [data-testid="stSidebar"] *, 
    [data-testid="stSidebar"] p, 
    [data-testid="stSidebar"] span, 
    [data-testid="stSidebar"] label, 
    [data-testid="stSidebar"] h1, 
    [data-testid="stSidebar"] h2, 
    [data-testid="stSidebar"] h3 {
        color: #ffffff !important;
    }
    
    /* Styled metric cards */
    .stMetric {
        background-color: #1e222d;
        padding: 12px;
        border-radius: 8px;
        border: 1px solid #2e364f;
        margin-bottom: 10px;
    }
    .stMetric label {
        color: #00d4ff !important;
        font-weight: 600;
    }
    </style>
""", unsafe_allow_html=True)

# Compact, single-line header
st.markdown("<h3 style='margin-bottom:0px; white-space: nowrap;'>📈 VR Predictive Analytics — Executive Business Forecasting</h3>", unsafe_allow_html=True)
st.caption("Interactive 3D Visual Analytics & Real-Time Predictive Simulation")

# 1. Historical Business Data Generation
@st.cache_data
def load_business_data():
    np.random.seed(42)
    n = 150
    mkt_budget = np.random.uniform(50, 500, n)       # Marketing (R'000)
    unit_price = np.random.uniform(20, 150, n)        # Unit Price (R)
    units_sold = (0.4 * mkt_budget) - (1.2 * unit_price) + np.random.normal(100, 25, n)
    units_sold = np.maximum(units_sold, 10)
    
    return pd.DataFrame({
        'MarketingBudget': np.round(mkt_budget, 2),
        'UnitPrice': np.round(unit_price, 2),
        'UnitsSold': np.round(units_sold, 2)
    })

df = load_business_data()

# 2. Train Forecasting Model
X = df[['MarketingBudget', 'UnitPrice']]
y = df['UnitsSold']
model = LinearRegression()
model.fit(X, y)

# 3. Enhanced Sidebar Controls & Dashboard
st.sidebar.markdown("## 🕹️ Control Panel")
st.sidebar.markdown("Tweak operational parameters to run real-time predictive simulations.")

st.sidebar.markdown("---")
st.sidebar.subheader("🎛️ Simulation Variables")

input_budget = st.sidebar.slider(
    "📢 Marketing Budget (R'000)", 
    float(df['MarketingBudget'].min()), 
    float(df['MarketingBudget'].max()), 
    250.0,
    step=5.0
)

input_price = st.sidebar.slider(
    "🏷️ Unit Price (R)", 
    float(df['UnitPrice'].min()), 
    float(df['UnitPrice'].max()), 
    85.0,
    step=1.0
)

# Real-Time Prediction Computation
input_data = pd.DataFrame([[input_budget, input_price]], columns=['MarketingBudget', 'UnitPrice'])
predicted_units = model.predict(input_data)[0]
predicted_revenue = (predicted_units * 1000) * input_price

st.sidebar.markdown("---")
st.sidebar.subheader("📊 Live Model Output")

st.sidebar.metric(
    label="Projected Sales Volume", 
    value=f"{predicted_units:.1f}k units",
    delta=f"{(predicted_units - df['UnitsSold'].mean()):.1f}k vs avg"
)

st.sidebar.metric(
    label="Estimated Gross Revenue", 
    value=f"R{predicted_revenue:,.2f}"
)

st.sidebar.markdown("---")
with st.sidebar.expander("ℹ️ Quick Lab Guide"):
    st.write("""
    * **Blue Surface:** Linear decision boundary generated by Scikit-Learn.
    * **Red Diamond:** Real-time prediction state based on your slider settings.
    * **Dots:** Historical performance baseline.
    """)

# 4. 3D Spatial Plotting (Full 700px Height)
fig = go.Figure()

# Historical Data Points
fig.add_trace(go.Scatter3d(
    x=df['MarketingBudget'],
    y=df['UnitPrice'],
    z=df['UnitsSold'],
    mode='markers',
    marker=dict(size=4, color=df['UnitsSold'], colorscale='Viridis', opacity=0.7),
    name='Historical Data'
))

# Interactive Prediction Marker
fig.add_trace(go.Scatter3d(
    x=[input_budget],
    y=[input_price],
    z=[predicted_units],
    mode='markers+text',
    marker=dict(size=10, color='red', symbol='diamond'),
    text=["Forecast Output"],
    textposition="top center",
    name="Current Target Point"
))

# Generate Regression Decision Surface
x_range = np.linspace(df['MarketingBudget'].min(), df['MarketingBudget'].max(), 10)
y_range = np.linspace(df['UnitPrice'].min(), df['UnitPrice'].max(), 10)
xx, yy = np.meshgrid(x_range, y_range)

grid_df = pd.DataFrame(np.c_[xx.ravel(), yy.ravel()], columns=['MarketingBudget', 'UnitPrice'])
zz = model.predict(grid_df).reshape(xx.shape)

fig.add_trace(go.Surface(
    x=xx,
    y=yy,
    z=zz,
    colorscale='Blues',
    opacity=0.35,
    showscale=False,
    name="Predictive Surface"
))

fig.update_layout(
    scene=dict(
        xaxis_title="Marketing Budget (R'000)",
        yaxis_title="Unit Price (R)",
        zaxis_title="Units Sold (k)",
        camera=dict(eye=dict(x=1.6, y=1.6, z=1.2))
    ),
    height=700,
    margin=dict(l=0, r=0, b=0, t=30)
)

st.plotly_chart(fig, use_container_width=True)